language: perl
env:
  - IN_TRAVIS=1
perl:
  - "dev"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
matrix:
  allow_failures:
    - perl: dev
    - perl: 5.8
sudo: false
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
