#!/usr/bin/env perl

use v5.10;

use FindBin;
use lib "$FindBin::Bin/../kubernetes-builder/lib/";

use strict;
use warnings;
use KubeBuilder;

$|=1;

my $builder = KubeBuilder->new(
  schema_file => 'spec/swagger.json'
);

$builder->process_template(
  'main_module',
  { builder => $builder },
);

$builder->process_template(
  'result2object',
  { builder => $builder },
);

foreach my $group (@{ $builder->method_groups_list }){
  $builder->log->info("Generating group class for group " . $group->name);
  $builder->process_template(
    'group',
    { group => $group },
  );
}

foreach my $m_name (sort keys %{ $builder->methods }){
  my $method = $builder->methods->{ $m_name };
  $builder->log->info("Generating method for definition $m_name");
  $builder->process_template(
    'method',
    { method => $method },
  );
}

